# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuser',
            name='test_name',
        ),
        migrations.AddField(
            model_name='impuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='impuser',
            name='tel',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
