# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_impuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuser',
            name='num',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='impuser',
            name='office',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
