# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-30 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('chn_name', models.CharField(blank=True, max_length=50)),
                ('IP', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.System')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
