# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_system_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_system',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.IMPUser'),
        ),
    ]
