# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180604_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=50)),
                ('host_type', models.CharField(blank=True, max_length=50)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.System')),
            ],
        ),
    ]
