# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-11 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_hosts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='chn_name',
            new_name='full_name',
        ),
    ]
