# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-11 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20180611_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
    ]
