# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=11)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('display_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
