# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('backgroundColor', models.CharField(max_length=6)),
                ('borderColor', models.CharField(max_length=6)),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
