# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='end_d',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='end_m',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='end_y',
            field=models.IntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='event',
            name='start_d',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='start_m',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='start_y',
            field=models.IntegerField(default=2018),
        ),
    ]
